### ISSUE TITLE
sdfsd

### ISSUE THREAD

**Issue by khalidharun** [hung-phan/rails-angular-require-template#1]
# Database Schema
## Customers
- created_at
- id
- profile_id
## Profiles
- id
- customer_id
- Firstname
- Lastname
- email
- phone number
- avater/photo
- languages
- gender
- birthdate
- Where you live
- description
- school
- work
- timezone
- emergency contact
## Listings
- id
- customer_id
- Calendar?
- Price
- Title
- Summary 
- Photo gallery
- Ameneties?
- Listing info
  - Bedrooms
  - Bath
  - Beds
  - Home_type
  - room_type (entire home, private room, shared room)
  - accomodates 
  - address
## Reservations
- customer_id
- listing_id
- dates
- final_price
- status 
## GuestReviews
- id
- guest_id
- host_id
- listing_id
- rating
- comment
- would you recommend?
## HostReviews
- id
- host_id
- customer_id
- listing_id
- rating (1 thru 5)
- optional text
- would you recommend to others?
## Messages
- timestamp
- reservation_id
- from_customer_id

**Comment by hung-phan** [comment]
:))

**Comment by khalidharun** [comment]
sorry about that. I had too many tabs open.  I would appreciate it if you
could please delete that issue.  Thanks!

I love to see to good generators.. thanks for you contribution.

**Comment by hung-phan** [comment]
I don't think Github allows to delete issue for now, according to https://github.com/isaacs/github/issues/253. However, thanks for using my generators @khalidharun.
